CREATE TABLE TRTR(
	MID VARCHAR(20) PRIMARY KEY,
	MPW VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	ROLE VARCHAR(10) NOT NULL
);

INSERT INTO TRTR VALUES('admin','1234','°ü¸®ÀÚ','ADMIN');
select * from TRTR;